//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasksReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", ConfigurationName="TasksReference.Task_ARGGOBEST_Port")]
    public interface Task_ARGGOBEST_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/task_arggobest:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TasksReference.Read_Result> ReadAsync(TasksReference.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/task_arggobest:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TasksReference.ReadByRecId_Result> ReadByRecIdAsync(TasksReference.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/task_arggobest:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TasksReference.ReadMultiple_Result> ReadMultipleAsync(TasksReference.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/task_arggobest:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TasksReference.IsUpdated_Result> IsUpdatedAsync(TasksReference.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/task_arggobest:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TasksReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(TasksReference.GetRecIdFromKey request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/task_arggobest:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TasksReference.Create_Result> CreateAsync(TasksReference.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/task_arggobest:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TasksReference.CreateMultiple_Result> CreateMultipleAsync(TasksReference.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/task_arggobest:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TasksReference.Update_Result> UpdateAsync(TasksReference.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/task_arggobest:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TasksReference.UpdateMultiple_Result> UpdateMultipleAsync(TasksReference.UpdateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/task_arggobest:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TasksReference.Delete_Result> DeleteAsync(TasksReference.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest")]
    public partial class Task_ARGGOBEST
    {
        
        private string keyField;
        
        private int task_IDField;
        
        private bool task_IDFieldSpecified;
        
        private int project_IDField;
        
        private bool project_IDFieldSpecified;
        
        private string task_TitleField;
        
        private string task_DescriptionField;
        
        private Priority priorityField;
        
        private bool priorityFieldSpecified;
        
        private decimal estimated_Analysis_HoursField;
        
        private bool estimated_Analysis_HoursFieldSpecified;
        
        private decimal estimated_Design_HoursField;
        
        private bool estimated_Design_HoursFieldSpecified;
        
        private decimal estimated_Development_HoursField;
        
        private bool estimated_Development_HoursFieldSpecified;
        
        private decimal estimated_Testing_HoursField;
        
        private bool estimated_Testing_HoursFieldSpecified;
        
        private System.DateTime required_Due_DateField;
        
        private bool required_Due_DateFieldSpecified;
        
        private System.DateTime estimated_Analysis_Due_DateField;
        
        private bool estimated_Analysis_Due_DateFieldSpecified;
        
        private System.DateTime estimated_Design_Due_DateField;
        
        private bool estimated_Design_Due_DateFieldSpecified;
        
        private System.DateTime estimated_Development_Due_DateField;
        
        private bool estimated_Development_Due_DateFieldSpecified;
        
        private System.DateTime estimated_Testing_Due_DateField;
        
        private bool estimated_Testing_Due_DateFieldSpecified;
        
        private System.DateTime actual_Analysis_Due_DateField;
        
        private bool actual_Analysis_Due_DateFieldSpecified;
        
        private System.DateTime actual_Design_Due_DateField;
        
        private bool actual_Design_Due_DateFieldSpecified;
        
        private System.DateTime actual_Development_Due_DateField;
        
        private bool actual_Development_Due_DateFieldSpecified;
        
        private System.DateTime actual_Testing_Due_DateField;
        
        private bool actual_Testing_Due_DateFieldSpecified;
        
        private decimal actual_Analysis_HoursField;
        
        private bool actual_Analysis_HoursFieldSpecified;
        
        private decimal actual_Design_HoursField;
        
        private bool actual_Design_HoursFieldSpecified;
        
        private decimal actual_Development_HoursField;
        
        private bool actual_Development_HoursFieldSpecified;
        
        private decimal actual_Testing_HoursField;
        
        private bool actual_Testing_HoursFieldSpecified;
        
        private Initial_Task_Type initial_Task_TypeField;
        
        private bool initial_Task_TypeFieldSpecified;
        
        private Current_Task_Type current_Task_TypeField;
        
        private bool current_Task_TypeFieldSpecified;
        
        private string license_DetailsField;
        
        private int owner_User_IDField;
        
        private bool owner_User_IDFieldSpecified;
        
        private string task_ResolutionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Task_ID
        {
            get
            {
                return this.task_IDField;
            }
            set
            {
                this.task_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Task_IDSpecified
        {
            get
            {
                return this.task_IDFieldSpecified;
            }
            set
            {
                this.task_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Project_ID
        {
            get
            {
                return this.project_IDField;
            }
            set
            {
                this.project_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Project_IDSpecified
        {
            get
            {
                return this.project_IDFieldSpecified;
            }
            set
            {
                this.project_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Task_Title
        {
            get
            {
                return this.task_TitleField;
            }
            set
            {
                this.task_TitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Task_Description
        {
            get
            {
                return this.task_DescriptionField;
            }
            set
            {
                this.task_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Priority Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritySpecified
        {
            get
            {
                return this.priorityFieldSpecified;
            }
            set
            {
                this.priorityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal Estimated_Analysis_Hours
        {
            get
            {
                return this.estimated_Analysis_HoursField;
            }
            set
            {
                this.estimated_Analysis_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Estimated_Analysis_HoursSpecified
        {
            get
            {
                return this.estimated_Analysis_HoursFieldSpecified;
            }
            set
            {
                this.estimated_Analysis_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal Estimated_Design_Hours
        {
            get
            {
                return this.estimated_Design_HoursField;
            }
            set
            {
                this.estimated_Design_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Estimated_Design_HoursSpecified
        {
            get
            {
                return this.estimated_Design_HoursFieldSpecified;
            }
            set
            {
                this.estimated_Design_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal Estimated_Development_Hours
        {
            get
            {
                return this.estimated_Development_HoursField;
            }
            set
            {
                this.estimated_Development_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Estimated_Development_HoursSpecified
        {
            get
            {
                return this.estimated_Development_HoursFieldSpecified;
            }
            set
            {
                this.estimated_Development_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal Estimated_Testing_Hours
        {
            get
            {
                return this.estimated_Testing_HoursField;
            }
            set
            {
                this.estimated_Testing_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Estimated_Testing_HoursSpecified
        {
            get
            {
                return this.estimated_Testing_HoursFieldSpecified;
            }
            set
            {
                this.estimated_Testing_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=10)]
        public System.DateTime Required_Due_Date
        {
            get
            {
                return this.required_Due_DateField;
            }
            set
            {
                this.required_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Required_Due_DateSpecified
        {
            get
            {
                return this.required_Due_DateFieldSpecified;
            }
            set
            {
                this.required_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=11)]
        public System.DateTime Estimated_Analysis_Due_Date
        {
            get
            {
                return this.estimated_Analysis_Due_DateField;
            }
            set
            {
                this.estimated_Analysis_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Estimated_Analysis_Due_DateSpecified
        {
            get
            {
                return this.estimated_Analysis_Due_DateFieldSpecified;
            }
            set
            {
                this.estimated_Analysis_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=12)]
        public System.DateTime Estimated_Design_Due_Date
        {
            get
            {
                return this.estimated_Design_Due_DateField;
            }
            set
            {
                this.estimated_Design_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Estimated_Design_Due_DateSpecified
        {
            get
            {
                return this.estimated_Design_Due_DateFieldSpecified;
            }
            set
            {
                this.estimated_Design_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=13)]
        public System.DateTime Estimated_Development_Due_Date
        {
            get
            {
                return this.estimated_Development_Due_DateField;
            }
            set
            {
                this.estimated_Development_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Estimated_Development_Due_DateSpecified
        {
            get
            {
                return this.estimated_Development_Due_DateFieldSpecified;
            }
            set
            {
                this.estimated_Development_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=14)]
        public System.DateTime Estimated_Testing_Due_Date
        {
            get
            {
                return this.estimated_Testing_Due_DateField;
            }
            set
            {
                this.estimated_Testing_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Estimated_Testing_Due_DateSpecified
        {
            get
            {
                return this.estimated_Testing_Due_DateFieldSpecified;
            }
            set
            {
                this.estimated_Testing_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=15)]
        public System.DateTime Actual_Analysis_Due_Date
        {
            get
            {
                return this.actual_Analysis_Due_DateField;
            }
            set
            {
                this.actual_Analysis_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Analysis_Due_DateSpecified
        {
            get
            {
                return this.actual_Analysis_Due_DateFieldSpecified;
            }
            set
            {
                this.actual_Analysis_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=16)]
        public System.DateTime Actual_Design_Due_Date
        {
            get
            {
                return this.actual_Design_Due_DateField;
            }
            set
            {
                this.actual_Design_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Design_Due_DateSpecified
        {
            get
            {
                return this.actual_Design_Due_DateFieldSpecified;
            }
            set
            {
                this.actual_Design_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=17)]
        public System.DateTime Actual_Development_Due_Date
        {
            get
            {
                return this.actual_Development_Due_DateField;
            }
            set
            {
                this.actual_Development_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Development_Due_DateSpecified
        {
            get
            {
                return this.actual_Development_Due_DateFieldSpecified;
            }
            set
            {
                this.actual_Development_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=18)]
        public System.DateTime Actual_Testing_Due_Date
        {
            get
            {
                return this.actual_Testing_Due_DateField;
            }
            set
            {
                this.actual_Testing_Due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Testing_Due_DateSpecified
        {
            get
            {
                return this.actual_Testing_Due_DateFieldSpecified;
            }
            set
            {
                this.actual_Testing_Due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public decimal Actual_Analysis_Hours
        {
            get
            {
                return this.actual_Analysis_HoursField;
            }
            set
            {
                this.actual_Analysis_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Analysis_HoursSpecified
        {
            get
            {
                return this.actual_Analysis_HoursFieldSpecified;
            }
            set
            {
                this.actual_Analysis_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal Actual_Design_Hours
        {
            get
            {
                return this.actual_Design_HoursField;
            }
            set
            {
                this.actual_Design_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Design_HoursSpecified
        {
            get
            {
                return this.actual_Design_HoursFieldSpecified;
            }
            set
            {
                this.actual_Design_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal Actual_Development_Hours
        {
            get
            {
                return this.actual_Development_HoursField;
            }
            set
            {
                this.actual_Development_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Development_HoursSpecified
        {
            get
            {
                return this.actual_Development_HoursFieldSpecified;
            }
            set
            {
                this.actual_Development_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public decimal Actual_Testing_Hours
        {
            get
            {
                return this.actual_Testing_HoursField;
            }
            set
            {
                this.actual_Testing_HoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Actual_Testing_HoursSpecified
        {
            get
            {
                return this.actual_Testing_HoursFieldSpecified;
            }
            set
            {
                this.actual_Testing_HoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public Initial_Task_Type Initial_Task_Type
        {
            get
            {
                return this.initial_Task_TypeField;
            }
            set
            {
                this.initial_Task_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Initial_Task_TypeSpecified
        {
            get
            {
                return this.initial_Task_TypeFieldSpecified;
            }
            set
            {
                this.initial_Task_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public Current_Task_Type Current_Task_Type
        {
            get
            {
                return this.current_Task_TypeField;
            }
            set
            {
                this.current_Task_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Current_Task_TypeSpecified
        {
            get
            {
                return this.current_Task_TypeFieldSpecified;
            }
            set
            {
                this.current_Task_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string License_Details
        {
            get
            {
                return this.license_DetailsField;
            }
            set
            {
                this.license_DetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int Owner_User_ID
        {
            get
            {
                return this.owner_User_IDField;
            }
            set
            {
                this.owner_User_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Owner_User_IDSpecified
        {
            get
            {
                return this.owner_User_IDFieldSpecified;
            }
            set
            {
                this.owner_User_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Task_Resolution
        {
            get
            {
                return this.task_ResolutionField;
            }
            set
            {
                this.task_ResolutionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest")]
    public enum Priority
    {
        
        /// <remarks/>
        Low,
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        High,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest")]
    public enum Initial_Task_Type
    {
        
        /// <remarks/>
        Bug,
        
        /// <remarks/>
        Change_Request,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest")]
    public enum Current_Task_Type
    {
        
        /// <remarks/>
        Bug,
        
        /// <remarks/>
        Change_Request,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest")]
    public partial class Task_ARGGOBEST_Filter
    {
        
        private Task_ARGGOBEST_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Task_ARGGOBEST_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest")]
    public enum Task_ARGGOBEST_Fields
    {
        
        /// <remarks/>
        Task_ID,
        
        /// <remarks/>
        Project_ID,
        
        /// <remarks/>
        Task_Title,
        
        /// <remarks/>
        Task_Description,
        
        /// <remarks/>
        Priority,
        
        /// <remarks/>
        Estimated_Analysis_Hours,
        
        /// <remarks/>
        Estimated_Design_Hours,
        
        /// <remarks/>
        Estimated_Development_Hours,
        
        /// <remarks/>
        Estimated_Testing_Hours,
        
        /// <remarks/>
        Required_Due_Date,
        
        /// <remarks/>
        Estimated_Analysis_Due_Date,
        
        /// <remarks/>
        Estimated_Design_Due_Date,
        
        /// <remarks/>
        Estimated_Development_Due_Date,
        
        /// <remarks/>
        Estimated_Testing_Due_Date,
        
        /// <remarks/>
        Actual_Analysis_Due_Date,
        
        /// <remarks/>
        Actual_Design_Due_Date,
        
        /// <remarks/>
        Actual_Development_Due_Date,
        
        /// <remarks/>
        Actual_Testing_Due_Date,
        
        /// <remarks/>
        Actual_Analysis_Hours,
        
        /// <remarks/>
        Actual_Design_Hours,
        
        /// <remarks/>
        Actual_Development_Hours,
        
        /// <remarks/>
        Actual_Testing_Hours,
        
        /// <remarks/>
        Initial_Task_Type,
        
        /// <remarks/>
        Current_Task_Type,
        
        /// <remarks/>
        License_Details,
        
        /// <remarks/>
        Owner_User_ID,
        
        /// <remarks/>
        Task_Resolution,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        public int Task_ID;
        
        public Read()
        {
        }
        
        public Read(int Task_ID)
        {
            this.Task_ID = Task_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        public TasksReference.Task_ARGGOBEST Task_ARGGOBEST;
        
        public Read_Result()
        {
        }
        
        public Read_Result(TasksReference.Task_ARGGOBEST Task_ARGGOBEST)
        {
            this.Task_ARGGOBEST = Task_ARGGOBEST;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        public TasksReference.Task_ARGGOBEST Task_ARGGOBEST;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(TasksReference.Task_ARGGOBEST Task_ARGGOBEST)
        {
            this.Task_ARGGOBEST = Task_ARGGOBEST;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public TasksReference.Task_ARGGOBEST_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(TasksReference.Task_ARGGOBEST_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TasksReference.Task_ARGGOBEST[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(TasksReference.Task_ARGGOBEST[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        public TasksReference.Task_ARGGOBEST Task_ARGGOBEST;
        
        public Create()
        {
        }
        
        public Create(TasksReference.Task_ARGGOBEST Task_ARGGOBEST)
        {
            this.Task_ARGGOBEST = Task_ARGGOBEST;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        public TasksReference.Task_ARGGOBEST Task_ARGGOBEST;
        
        public Create_Result()
        {
        }
        
        public Create_Result(TasksReference.Task_ARGGOBEST Task_ARGGOBEST)
        {
            this.Task_ARGGOBEST = Task_ARGGOBEST;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TasksReference.Task_ARGGOBEST[] Task_ARGGOBEST_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(TasksReference.Task_ARGGOBEST[] Task_ARGGOBEST_List)
        {
            this.Task_ARGGOBEST_List = Task_ARGGOBEST_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TasksReference.Task_ARGGOBEST[] Task_ARGGOBEST_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(TasksReference.Task_ARGGOBEST[] Task_ARGGOBEST_List)
        {
            this.Task_ARGGOBEST_List = Task_ARGGOBEST_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        public TasksReference.Task_ARGGOBEST Task_ARGGOBEST;
        
        public Update()
        {
        }
        
        public Update(TasksReference.Task_ARGGOBEST Task_ARGGOBEST)
        {
            this.Task_ARGGOBEST = Task_ARGGOBEST;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        public TasksReference.Task_ARGGOBEST Task_ARGGOBEST;
        
        public Update_Result()
        {
        }
        
        public Update_Result(TasksReference.Task_ARGGOBEST Task_ARGGOBEST)
        {
            this.Task_ARGGOBEST = Task_ARGGOBEST;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TasksReference.Task_ARGGOBEST[] Task_ARGGOBEST_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(TasksReference.Task_ARGGOBEST[] Task_ARGGOBEST_List)
        {
            this.Task_ARGGOBEST_List = Task_ARGGOBEST_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TasksReference.Task_ARGGOBEST[] Task_ARGGOBEST_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(TasksReference.Task_ARGGOBEST[] Task_ARGGOBEST_List)
        {
            this.Task_ARGGOBEST_List = Task_ARGGOBEST_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/task_arggobest", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/task_arggobest", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface Task_ARGGOBEST_PortChannel : TasksReference.Task_ARGGOBEST_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class Task_ARGGOBEST_PortClient : System.ServiceModel.ClientBase<TasksReference.Task_ARGGOBEST_Port>, TasksReference.Task_ARGGOBEST_Port
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Task_ARGGOBEST_PortClient() : 
                base(Task_ARGGOBEST_PortClient.GetDefaultBinding(), Task_ARGGOBEST_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Task_ARGGOBEST_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Task_ARGGOBEST_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(Task_ARGGOBEST_PortClient.GetBindingForEndpoint(endpointConfiguration), Task_ARGGOBEST_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Task_ARGGOBEST_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Task_ARGGOBEST_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Task_ARGGOBEST_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Task_ARGGOBEST_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Task_ARGGOBEST_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TasksReference.Read_Result> TasksReference.Task_ARGGOBEST_Port.ReadAsync(TasksReference.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<TasksReference.Read_Result> ReadAsync(int Task_ID)
        {
            TasksReference.Read inValue = new TasksReference.Read();
            inValue.Task_ID = Task_ID;
            return ((TasksReference.Task_ARGGOBEST_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TasksReference.ReadByRecId_Result> TasksReference.Task_ARGGOBEST_Port.ReadByRecIdAsync(TasksReference.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TasksReference.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            TasksReference.ReadByRecId inValue = new TasksReference.ReadByRecId();
            inValue.recId = recId;
            return ((TasksReference.Task_ARGGOBEST_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TasksReference.ReadMultiple_Result> TasksReference.Task_ARGGOBEST_Port.ReadMultipleAsync(TasksReference.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<TasksReference.ReadMultiple_Result> ReadMultipleAsync(TasksReference.Task_ARGGOBEST_Filter[] filter, string bookmarkKey, int setSize)
        {
            TasksReference.ReadMultiple inValue = new TasksReference.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((TasksReference.Task_ARGGOBEST_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TasksReference.IsUpdated_Result> TasksReference.Task_ARGGOBEST_Port.IsUpdatedAsync(TasksReference.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<TasksReference.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            TasksReference.IsUpdated inValue = new TasksReference.IsUpdated();
            inValue.Key = Key;
            return ((TasksReference.Task_ARGGOBEST_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TasksReference.GetRecIdFromKey_Result> TasksReference.Task_ARGGOBEST_Port.GetRecIdFromKeyAsync(TasksReference.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<TasksReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            TasksReference.GetRecIdFromKey inValue = new TasksReference.GetRecIdFromKey();
            inValue.Key = Key;
            return ((TasksReference.Task_ARGGOBEST_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<TasksReference.Create_Result> CreateAsync(TasksReference.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<TasksReference.CreateMultiple_Result> CreateMultipleAsync(TasksReference.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<TasksReference.Update_Result> UpdateAsync(TasksReference.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<TasksReference.UpdateMultiple_Result> UpdateMultipleAsync(TasksReference.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TasksReference.Delete_Result> TasksReference.Task_ARGGOBEST_Port.DeleteAsync(TasksReference.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TasksReference.Delete_Result> DeleteAsync(string Key)
        {
            TasksReference.Delete inValue = new TasksReference.Delete();
            inValue.Key = Key;
            return ((TasksReference.Task_ARGGOBEST_Port)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Task_ARGGOBEST_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Task_ARGGOBEST_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://nav2018.arggo.consulting:7052/ARGGOBEST/WS/Cronus03/Page/Task_ARGGOBEST?ws" +
                        "dl");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Task_ARGGOBEST_PortClient.GetBindingForEndpoint(EndpointConfiguration.Task_ARGGOBEST_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Task_ARGGOBEST_PortClient.GetEndpointAddress(EndpointConfiguration.Task_ARGGOBEST_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            Task_ARGGOBEST_Port,
        }
    }
}
